[package]
name = "toad-java-glue"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.21.1"
toad = "0.17.2"
toad-jni = "0.4.1"
toad-msg = "0.18.1"
tinyvec = {version = "1.5", default_features = false, features = ["rustc_1_55"]}
